version: '3.8'

services:
  backend:
    image: maelmichaud/node-backend:latest
    container_name: node-backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
    depends_on:
      - postgres-db

  frontend:
    image: maelmichaud/react-frontend:latest
    container_name: react-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend

  postgres-db:
    image: postgres:14
    container_name: postgres-db
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata: