name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Backend CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configuration de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Installation des dépendances du backend
        working-directory: ./backend
        run: npm install

      - name: Build du backend
        working-directory: ./backend
        run: npm run build

  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configuration de Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Installation des dépendances du frontend
        working-directory: ./frontend
        run: npm install

      - name: Build du frontend
        working-directory: ./frontend
        run: npm run build

  docker-backend:
    name: Build Docker Image - Backend
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Build Docker image - backend
        run: docker build -t backend-image:latest ./backend

  docker-frontend:
    name: Build Docker Image - Frontend
    runs-on: ubuntu-latest
    needs: frontend
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Build Docker image - frontend
        run: docker build -t frontend-image:latest ./frontend
